#ifndef DECODER_TB_H
#define DECODER_TB_H

#include "Vdecoder_decoder.h"

#define DECODER_SIG(SIG) Vdecoder_decoder::_IData##SIG::SIG

#define  A_SRC_PC  DECODER_SIG(A_SRC_PC)
#define  A_SRC_RS1 DECODER_SIG(A_SRC_RS1)
#define  B_SRC_IMM DECODER_SIG(B_SRC_IMM)
#define  B_SRC_RS2 DECODER_SIG(B_SRC_RS2)

#define ALU_OP_ADD  DECODER_SIG(ALU_OP_ADD)
#define ALU_OP_SHL  DECODER_SIG(ALU_OP_SHL)
#define ALU_OP_CMP  DECODER_SIG(ALU_OP_CMP)
#define ALU_OP_CMPU DECODER_SIG(ALU_OP_CMPU)
#define ALU_OP_XOR  DECODER_SIG(ALU_OP_XOR)
#define ALU_OP_SHR  DECODER_SIG(ALU_OP_SHR)
#define ALU_OP_OR   DECODER_SIG(ALU_OP_OR)
#define ALU_OP_AND  DECODER_SIG(ALU_OP_AND)

#define NEXT_PC_ALU DECODER_SIG(NEXT_PC_ALU)
#define NEXT_PC_INC DECODER_SIG(NEXT_PC_INC)
#define NEXT_PC_BR0 DECODER_SIG(NEXT_PC_BR0)
#define NEXT_PC_BR1 DECODER_SIG(NEXT_PC_BR1)

#define WB_SRC_PC  DECODER_SIG(WB_SRC_PC)
#define WB_SRC_MEM DECODER_SIG(WB_SRC_MEM)
#define WB_SRC_ALU DECODER_SIG(WB_SRC_ALU)
#define WB_SRC_CSR DECODER_SIG(WB_SRC_CSR)

#endif
